AWSTemplateFormatVersion: "2010-09-09"

Description: Template of practice-cfn

Parameters:
  NameBase:
    Description: Name tag Value
    Type: String
    Default: practice-cfn
  MySQLMajorVersion:
    Type: String
    Default: "5.7"
    AllowedValues: [ "8.0", "5.6", "5.7" ]
  MySQLMinorVersion:
    Type: String
    Default: "27"
  DBMasterUserName:
    Type: String
    Default: "root"
    NoEcho: true
    MinLength: 1
    MaxLength: 16
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*"
    ConstraintDescription: "must begin with a letter and contain only alphanumeric characters."
  DBPassword: 
    Default: "dbpassword"
    NoEcho: true
    Type: String
    MinLength: 8
    MaxLength: 41
    AllowedPattern: "[a-zA-Z0-9]*"
    ConstraintDescription: "must contain only alphanumeric characters."
  DBName:
    Type: String
    Default: practice2cfn2db

Resources:
  # RDS
  DBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: "16"
      DBInstanceClass: db.t2.micro
      AvailabilityZone: ap-northeast-1a
      BackupRetentionPeriod: "7"
      DBInstanceIdentifier: !Sub ${NameBase}-rds
      DBName: !Ref DBName
      DBParameterGroupName: !Ref DBParameterGroup
      DBSubnetGroupName: !Ref DBSubnetGroup
      Engine: mysql
      EngineVersion: !Sub ${MySQLMajorVersion}.${MySQLMinorVersion}
      MasterUsername: !Ref DBMasterUserName
      MasterUserPassword: !Ref DBPassword
      MultiAZ: "false"
      PreferredBackupWindow: "18:00-18:30"
      PreferredMaintenanceWindow: "sat:19:00-sat:19:30"
      PubliclyAccessible: "false"
      StorageType: gp2
      VPCSecurityGroups:
        - !Ref RDSSecurityGroup
      Tags:
        - Key: Name
          Value: !Sub ${NameBase}-rds
    DeletionPolicy: "Delete"
  # パラメータグループ
  DBParameterGroup:
    Type: "AWS::RDS::DBParameterGroup"
    Properties:
      Family: !Sub "MySQL${MySQLMajorVersion}"
      Description: !Sub "${NameBase}-mysql80"
  # セキュリティグループ
  RDSSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      VpcId: !ImportValue myVPC
      GroupName: !Sub "${NameBase}-rds-sg"
      GroupDescription: !Sub "${NameBase}-rds-sg"
      Tags:
        - Key: "Name"
          Value: !Sub "${NameBase}-rds-sg"
      SecurityGroupIngress:
        # MySQL/Aurora
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          SourceSecurityGroupId: !ImportValue EC2SG
  # サブネットグループ
  DBSubnetGroup: 
    Type: "AWS::RDS::DBSubnetGroup"
    Properties: 
      DBSubnetGroupName: !Sub "${NameBase}-dbsub-gp"
      DBSubnetGroupDescription: !Sub "${NameBase}-dbsub-gp"
      SubnetIds: 
        - !ImportValue PriSub1a
        - !ImportValue PriSub1c

Outputs:

  DBInstanceID:
    Value: !Ref DBInstance
    Export:
      Name: DBInstance

  DBInstanceEndpoint:
    Value: !GetAtt DBInstance.Endpoint.Address
    Export:
      Name: DBInstanceEndpoint

  DBName:
    Value: !Ref DBName
    Export:
      Name: DBName